from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

SKIDL_lib_version = '0.0.1'

main_lib = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'PWR_FLAG', 'dest':TEMPLATE, 'tool':SKIDL, 'num_units':1, 'ref_prefix':'#FLG', '_aliases':Alias({'PWR_FLAG'}), '_match_pin_regex':False, 'pin':None, '_name':'PWR_FLAG', 'datasheet':'~', 'aliases':Alias({'PWR_FLAG'}), 'fplist':[], 'keywords':'power-flag', 'do_erc':True, 'description':'Special symbol for telling ERC where power comes from', 'footprint':'Power:Flag', 'pins':[
            Pin(num='1',name='pwr',func=Pin.types.PWRIN,do_erc=True)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'num_units':1, 'ref_prefix':'R', '_aliases':Alias({'R'}), '_match_pin_regex':False, 'pin':None, '_name':'R', 'datasheet':'~', 'aliases':Alias({'R'}), 'fplist':['R_*'], 'keywords':'R res resistor', 'do_erc':True, 'description':'Resistor', 'footprint':'Resistor_SMD:R_0805_2012Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'LM2902', 'dest':TEMPLATE, 'tool':SKIDL, 'num_units':5, 'ref_prefix':'U', '_aliases':Alias({'TL074', 'MCP6L94', 'TSV914', 'MC33179', 'LMC6484', 'MC33079', 'TL084', 'OPA4340UA', 'LM2902', 'TSV994', 'TLC274', 'MCP6004', 'ADA4807-4', 'OPA1679', 'LMV324', 'OPA1604', 'OPA4376', 'LM324', 'OPA4134', 'LM324A', 'MCP604', 'TLC279', 'TL064', 'MC33174'}), '_match_pin_regex':False, 'pin':None, '_name':'LM2902', 'datasheet':'https://www.st.com/resource/en/datasheet/tsv994.pdf', 'aliases':Alias({'TL074', 'MCP6L94', 'TSV914', 'MC33179', 'LMC6484', 'MC33079', 'TL084', 'OPA4340UA', 'LM2902', 'TSV994', 'TLC274', 'MCP6004', 'ADA4807-4', 'OPA1679', 'LMV324', 'OPA1604', 'OPA4376', 'LM324', 'OPA4134', 'LM324A', 'MCP604', 'TLC279', 'TL064', 'MC33174'}), 'fplist':['SOIC*3.9x8.7mm*P1.27mm*', 'DIP*W7.62mm*', 'TSSOP*4.4x5mm*P0.65mm*', 'SSOP*5.3x6.2mm*P0.65mm*', 'MSOP*3x3mm*P0.5mm*'], 'keywords':'quad opamp', 'do_erc':True, 'description':'Quad Rail-to-rail, 20 MHz GBP, operational amplifiers, SOIC-14/TSSOP-14', 'footprint':'Package_SO:SOIC-14_3.9x8.7mm_P1.27mm', 'pins':[
            Pin(num='1',name='~',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='2',name='-',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='+',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='+',func=Pin.types.INPUT,do_erc=True),
            Pin(num='6',name='-',func=Pin.types.INPUT,do_erc=True),
            Pin(num='7',name='~',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='10',name='+',func=Pin.types.INPUT,do_erc=True),
            Pin(num='8',name='~',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='9',name='-',func=Pin.types.INPUT,do_erc=True),
            Pin(num='12',name='+',func=Pin.types.INPUT,do_erc=True),
            Pin(num='13',name='-',func=Pin.types.INPUT,do_erc=True),
            Pin(num='14',name='~',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='11',name='V-',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='4',name='V+',func=Pin.types.PWRIN,do_erc=True)] }),
        Part(**{ 'name':'2N3904', 'dest':TEMPLATE, 'tool':SKIDL, 'num_units':1, 'ref_prefix':'Q', '_aliases':Alias({'2N3904'}), '_match_pin_regex':False, 'pin':None, '_name':'2N3904', 'datasheet':'https://www.fairchildsemi.com/datasheets/2N/2N3904.pdf', 'aliases':Alias({'2N3904'}), 'fplist':['TO?92*'], 'keywords':'NPN Transistor', 'do_erc':True, 'description':'0.2A Ic, 40V Vce, Small Signal NPN Transistor, TO-92', 'footprint':'Package_TO_SOT_THT:TO-92_Inline', 'pins':[
            Pin(num='1',name='E',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='B',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='C',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'Conn_01x04', 'dest':TEMPLATE, 'tool':SKIDL, 'num_units':1, 'ref_prefix':'J', '_aliases':Alias({'Conn_01x04'}), '_match_pin_regex':False, 'pin':None, '_name':'Conn_01x04', 'datasheet':'~', 'aliases':Alias({'Conn_01x04'}), 'fplist':['Connector*:*_1x??_*'], 'keywords':'connector', 'do_erc':True, 'description':'Generic connector, single row, 01x04, script generated (kicad-library-utils/schlib/autogen/connector/)', 'footprint':'Connector_PinHeader_1x04_P2.54mm_Vertical:PinHeader_1x04_P2.54mm_Vertical', 'pins':[
            Pin(num='1',name='Pin_1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='Pin_2',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='Pin_3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='Pin_4',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'AD8236', 'dest':TEMPLATE, 'tool':SKIDL, 'num_units':1, 'ref_prefix':'U', '_aliases':Alias({'AD8421', 'AD8236', 'AD8422', 'AD8429'}), '_match_pin_regex':False, 'pin':None, '_name':'AD8236', 'datasheet':'https://www.analog.com/media/en/technical-documentation/data-sheets/AD8429.pdf', 'aliases':Alias({'AD8421', 'AD8236', 'AD8422', 'AD8429'}), 'fplist':['SOIC*3.9x4.9mm*P1.27mm*', 'MSOP*3x3mm*P0.65mm*'], 'keywords':'single instumentation amplifier', 'do_erc':True, 'description':'Single Low Noise Instrumentation Amplifier, SOIC-8', 'footprint':'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'pins':[
            Pin(num='1',name='-',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='Rg',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='Rg',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='+',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='Vs-',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='6',name='Ref',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='7',name='~',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='8',name='Vs+',func=Pin.types.PWRIN,do_erc=True)] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'num_units':1, 'ref_prefix':'C', '_aliases':Alias({'C'}), '_match_pin_regex':False, 'pin':None, '_name':'C', 'datasheet':'~', 'aliases':Alias({'C'}), 'fplist':['C_*'], 'keywords':'cap capacitor', 'do_erc':True, 'description':'Unpolarized capacitor', 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'LM2903', 'dest':TEMPLATE, 'tool':SKIDL, 'num_units':3, 'ref_prefix':'U', '_aliases':Alias({'LM2903', 'LM393', 'LMV393', 'MCP6562', 'MCP6567'}), '_match_pin_regex':False, 'pin':None, '_name':'LM2903', 'datasheet':'http://www.farnell.com/datasheets/2133492.pdf', 'aliases':Alias({'LM2903', 'LM393', 'LMV393', 'MCP6562', 'MCP6567'}), 'fplist':['SOIC*3.9x4.9mm*P1.27mm*', 'DIP*W7.62mm*', 'MSOP*3x3mm*P0.65mm*', 'VSSOP*2.3x2mm*P0.5mm*'], 'keywords':'dual comparator', 'do_erc':True, 'description':'Dual 1.8V Low-Power Push-Pull Output Comparator, SOIC-8/MSOP-8', 'footprint':'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'pins':[
            Pin(num='1',name='~',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='2',name='-',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='+',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='+',func=Pin.types.INPUT,do_erc=True),
            Pin(num='6',name='_',func=Pin.types.INPUT,do_erc=True),
            Pin(num='7',name='~',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='4',name='V-',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='8',name='V+',func=Pin.types.PWRIN,do_erc=True)] }),
        Part(**{ 'name':'ESP32-S3-WROOM-2-N16R8V', 'dest':TEMPLATE, 'tool':SKIDL, 'num_units':1, 'ref_prefix':'U', '_aliases':Alias({'ESP32-S3-WROOM-2-N16R8V'}), '_match_pin_regex':False, 'pin':None, '_name':'ESP32-S3-WROOM-2-N16R8V', 'datasheet':'', 'aliases':Alias({'ESP32-S3-WROOM-2-N16R8V'}), 'fplist':[], 'keywords':'', 'do_erc':True, 'description':'', 'footprint':'ESP32-S3-WROOM-2:ESP32-S3-WROOM-2', 'pins':[
            Pin(num='1',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='40',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='41_1',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='41_2',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='41_3',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='41_4',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='41_5',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='41_6',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='41_7',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='41_8',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='41_9',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='2',name='3V3',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='3',name='EN',func=Pin.types.INPUT,do_erc=True),
            Pin(num='34',name='IO41',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='32',name='IO39',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='33',name='IO40',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='22',name='IO14',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='20',name='IO12',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='21',name='IO13',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='8',name='IO15',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='38',name='IO2',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='27',name='IO0',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='4',name='IO4',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='9',name='IO16',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='10',name='IO17',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='5',name='IO5',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='11',name='IO18',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='13',name='IO19',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='23',name='IO21',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='31',name='IO38',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='39',name='IO1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='15',name='IO3',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='6',name='IO6',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='7',name='IO7',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='12',name='IO8',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='17',name='IO9',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='18',name='IO10',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='19',name='IO11',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='35',name='IO42',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='14',name='IO20',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='37',name='TXD0',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='36',name='RXD0',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='26',name='IO45',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='16',name='IO46',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='24',name='IO47',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='25',name='IO48',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='28',name='NC',func=Pin.types.NOCONNECT,do_erc=True),
            Pin(num='29',name='NC',func=Pin.types.NOCONNECT,do_erc=True),
            Pin(num='30',name='NC',func=Pin.types.NOCONNECT,do_erc=True)] })])